[ns]
listen = "0.0.0.0:5800"
proxy = ""

[dontstarve]
cluster_name = "Neutron Star"
cluster_password = "6666"
cluster_description = "Just Have Fun"
game_mode = "endless"
max_players = 6
pvp = false
admin_list = []
cluster_token = ""
enable_mods = []
archive_name = "NeutronStar"

[tmodloader]
world_name = "NeutronStar"
auto_create = 3
difficulty = 2
seed = ""
password = "6666"
max_players = 8
port = 7777
enable_mods = []
