definitions:
  comm.RespErr:
    properties:
      code:
        type: integer
      detail:
        type: string
    type: object
  comm.RespOk:
    type: object
  core.ReportEvent:
    properties:
      level:
        type: string
      msg:
        type: string
      time:
        type: integer
      type:
        type: string
    type: object
  tmodloader.Mod:
    properties:
      config:
        type: string
      id:
        type: string
      name:
        type: string
      remark:
        type: string
    required:
    - id
    type: object
  tmodloader.ModMap:
    additionalProperties:
      $ref: '#/definitions/tmodloader.Mod'
    type: object
  tmodloader.ServerConfig:
    properties:
      auto_create:
        enum:
        - 1
        - 2
        - 3
        type: integer
      difficulty:
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
      enable_mods:
        items:
          type: string
        type: array
      max_players:
        type: integer
      password:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      seed:
        type: string
      world_name:
        type: string
    type: object
info:
  contact: {}
  title: Neutron Star
  version: "1.0"
paths:
  /tmodloader/control/{action}:
    post:
      consumes:
      - application/json
      parameters:
      - description: '[ start | stop | restart | update | install ]'
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 服务器控制
      tags:
      - tmodloader
  /tmodloader/events:
    get:
      consumes:
      - application/json
      description: 'ReportEvent Type: [ SERVER_ACTIVE ]'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.ReportEvent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取最近事件
      tags:
      - tmodloader
  /tmodloader/mod:
    delete:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 删除 Mods
      tags:
      - tmodloader
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tmodloader.ModMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 查看 Mods
      tags:
      - tmodloader
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 添加 Mods
      tags:
      - tmodloader
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 Mods
      tags:
      - tmodloader
  /tmodloader/runtime/players:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取当前玩家
      tags:
      - tmodloader
  /tmodloader/server_config:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tmodloader.ServerConfig'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取 ServerConfig
      tags:
      - tmodloader
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.ServerConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 ServerConfig
      tags:
      - tmodloader
swagger: "2.0"
