definitions:
  comm.RespErr:
    properties:
      code:
        type: integer
      detail:
        type: string
    type: object
  comm.RespOk:
    type: object
  core.ReportEvent:
    properties:
      level:
        type: string
      msg:
        type: string
      time:
        type: integer
      type:
        type: string
    type: object
  dontstarvetogether.Config:
    properties:
      admin_list:
        items:
          type: string
        type: array
      archive_name:
        type: string
      cluster_description:
        type: string
      cluster_name:
        type: string
      cluster_password:
        type: string
      cluster_token:
        type: string
      enable_mods:
        items:
          type: string
        type: array
      game_mode:
        type: string
      max_players:
        type: integer
      pvp:
        type: boolean
    type: object
  dontstarvetogether.Mod:
    properties:
      config:
        type: string
      id:
        type: string
      name:
        type: string
      remark:
        type: string
    required:
    - id
    type: object
  dontstarvetogether.ModMap:
    additionalProperties:
      $ref: '#/definitions/dontstarvetogether.Mod'
    type: object
  dontstarvetogether.Status:
    properties:
      status:
        type: integer
    type: object
  dontstarvetogether.WorldOverrides:
    properties:
      caves:
        type: string
      master:
        type: string
    type: object
  tmodloader.Config:
    properties:
      auto_create:
        enum:
        - 1
        - 2
        - 3
        type: integer
      difficulty:
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
      enable_mods:
        items:
          type: string
        type: array
      max_players:
        type: integer
      password:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      seed:
        type: string
      world_name:
        type: string
    type: object
  tmodloader.Mod:
    properties:
      config:
        type: string
      id:
        type: string
      name:
        type: string
      remark:
        type: string
    required:
    - id
    type: object
  tmodloader.ModMap:
    additionalProperties:
      $ref: '#/definitions/tmodloader.Mod'
    type: object
  tmodloader.Status:
    properties:
      status:
        type: integer
    type: object
info:
  contact: {}
  title: Neutron Star
  version: "1.0"
paths:
  /api/dontstarve/config:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dontstarvetogether.Config'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取 Config
      tags:
      - dontstarve
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dontstarvetogether.Config'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 Config
      tags:
      - dontstarve
  /api/dontstarve/control/{action}:
    post:
      consumes:
      - application/json
      parameters:
      - description: '[ start | stop | restart | update | install ]'
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 服务器控制
      tags:
      - dontstarve
  /api/dontstarve/event:
    get:
      consumes:
      - application/json
      description: 'ReportEvent Type: [ SERVER_ACTIVE ]'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.ReportEvent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取最近事件
      tags:
      - dontstarve
  /api/dontstarve/mod:
    delete:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 删除 Mods
      tags:
      - dontstarve
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dontstarvetogether.ModMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 查看 Mods
      tags:
      - dontstarve
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dontstarvetogether.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 添加 Mods
      tags:
      - dontstarve
    put:
      consumes:
      - application/json
      parameters:
      - description: '[ true | false ]'
        in: query
        name: update_mod_info
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dontstarvetogether.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 Mods
      tags:
      - dontstarve
  /api/dontstarve/mod/mod_id:
    post:
      consumes:
      - text/plain
      parameters:
      - description: 多个 Mod ID 一行一个
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 通过 Mod ID 添加 Mods
      tags:
      - dontstarve
  /api/dontstarve/runtime/announce/{msg}:
    post:
      consumes:
      - application/json
      parameters:
      - description: msg
        in: path
        name: msg
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 全服宣告
      tags:
      - dontstarve
  /api/dontstarve/runtime/player:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取当前玩家
      tags:
      - dontstarve
  /api/dontstarve/runtime/regenerate:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 重新生成世界
      tags:
      - dontstarve
  /api/dontstarve/runtime/rollback:
    post:
      consumes:
      - application/json
      parameters:
      - description: msg
        in: path
        name: times
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 回滚
      tags:
      - dontstarve
  /api/dontstarve/status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dontstarvetogether.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取服务器状态
      tags:
      - dontstarve
  /api/dontstarve/world_override:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dontstarvetogether.WorldOverrides'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取世界设置
      tags:
      - dontstarve
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dontstarvetogether.WorldOverrides'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新世界设置
      tags:
      - dontstarve
  /api/tmodloader/config:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tmodloader.Config'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取 Config
      tags:
      - tmodloader
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.Config'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 Config
      tags:
      - tmodloader
  /api/tmodloader/control/{action}:
    post:
      consumes:
      - application/json
      parameters:
      - description: '[ start | stop | restart | update | install ]'
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 服务器控制
      tags:
      - tmodloader
  /api/tmodloader/event:
    get:
      consumes:
      - application/json
      description: 'ReportEvent Type: [ SERVER_ACTIVE ]'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.ReportEvent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取最近事件
      tags:
      - tmodloader
  /api/tmodloader/mod:
    delete:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 删除 Mods
      tags:
      - tmodloader
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tmodloader.ModMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 查看 Mods
      tags:
      - tmodloader
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 添加 Mods
      tags:
      - tmodloader
    put:
      consumes:
      - application/json
      parameters:
      - description: '[ true | false ]'
        in: query
        name: update_mod_info
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tmodloader.ModMap'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 更新 Mods
      tags:
      - tmodloader
  /api/tmodloader/mod/mod_id:
    post:
      consumes:
      - text/plain
      parameters:
      - description: 多个 Mod ID 一行一个
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comm.RespOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 通过 Mod ID 添加 Mods
      tags:
      - tmodloader
  /api/tmodloader/runtime/player:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取当前玩家
      tags:
      - tmodloader
  /api/tmodloader/status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tmodloader.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/comm.RespErr'
      summary: 获取服务器状态
      tags:
      - tmodloader
swagger: "2.0"
